apiVersion: v1
kind: Service
metadata: 
  name: dlk-kafka-broker2-service
  namespace: dlk-kafka
spec: 
  clusterIP: None
  selector: 
    app: kafka-broker2
  ports: 
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
