crds:
  create: false

grafana:
  service:
    type: ClusterIP
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:084550838259:certificate/cde6b6e2-653d-4dff-82db-6b92fc1c7405"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  persistence:
    enabled: false

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    remoteWriteDashboards: false
    serverSideApply: true
    retention: 12h

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'slack-notifications'
      routes:
      - receiver: 'null'
        matchers:
          - alertname = "Watchdog"
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - send_resolved: true
            channel: "#alerts"
            api_url: "https://hooks.slack.com/services/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"
            title: "🔥 Alert: {{ .CommonAnnotations.summary }}"
            text: "{{ .CommonAnnotations.description }}"

