apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dlk-kafka-zookeeper
  namespace: dlk-kafka-zook
spec:
  serviceName: dlk-kafka-zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: dlk-kafka-zookeeper
  template:
    metadata:
      labels:
        app: dlk-kafka-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
        ports:
          - containerPort: 2181
            name: client
        volumeMounts:
          - name: zookeeper-data
            mountPath: /bitnami/zookeeper
        resources: 
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: zookeeper-data
          emptyDir: {}  

