apiVersion: v1
kind: Service
metadata:
  name: dlk-kafka-zookeeper
  namespace: dlk-kafka-zook
spec:
  clusterIP: None  
  selector:
    app: dlk-kafka-zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181

