apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-be-alcohol-alcohol-deploy
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: spring-container
          image: 192.168.3.81/dlink/alcohol-service:v1.0

