apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-fe-next-deploy
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nextjs-container
          image: 192.168.3.81/dlink/next-app:v1.0

