apiVersion: v1
kind: Service
metadata:
  name: dlk-be-alcohol-svc
  namespace: dlk-be-alcohol
spec:
  selector:
    app: alcohol-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

