apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-be-auth-auth-deploy
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
        - name: dlk-be-auth-ecr-secret
      containers:
        - name: spring-container
          image: 084550838259.dkr.ecr.ap-northeast-2.amazonaws.com/dlink/auth-service:v2.0.13
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: "AWS_ACCESS_KEY"
              value: "/mnt/secrets/AWS_ACCESS_KEY"
            - name: "AWS_SECRET_KEY"
              value: "/mnt/secrets/AWS_SECRET_KEY"
            - name: "GOOGLE_CLIENT_ID"
              value: "/mnt/secrets/GOOGLE_CLIENT_ID"
            - name: "GOOGLE_CLIENT_SECRET"
              value: "/mnt/secrets/GOOGLE_CLIENT_SECRET"
            - name: "KAKAO_CLIENT_SECRET"
              value: "/mnt/secrets/KAKAO_CLIENT_SECRET"
            - name: "KAKAO_REST_API"
              value: "/mnt/secrets/KAKAO_REST_API"
            - name: "NAVER_CLIENT_ID"
              value: "/mnt/secrets/NAVER_CLIENT_ID"
            - name: "NAVER_CLIENT_SECRET"
              value: "/mnt/secrets/NAVER_CLIENT_SECRET"
            - name: "NEXTAUTH_SECRET"
              value: "/mnt/secrets/NEXTAUTH_SECRET"
            - name: "ES_DATASOURCE_URI"
              value: "/mnt/secrets/ES_DATASOURCE_URI"
            - name: "JWT_SECRET_KEY"
              value: "/mnt/secrets/JWT_SECRET_KEY"
            - name: "SPRING_DATA_MONGODB_URI"
              value: "/mnt/secrets/SPRING_DATA_MONGODB_URI"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
