apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-gateway-gateway-deploy
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
        - name: dlk-gateway-ecr-secret
      containers:
        - name: alcohol-container
          image: 084550838259.dkr.ecr.ap-northeast-2.amazonaws.com/dlink/api-gateway:v3.0.3
