apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-fe-next-deploy
  namespace: dlk-fe-next
spec:
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      serviceAccountName: aws-secrets-sa
      imagePullSecrets:
        - name: dlk-fe-next-ecr-secret
      containers:
        - name: nextjs-container
          image: 084550838259.dkr.ecr.ap-northeast-2.amazonaws.com/dlink/next-app:v2.0.5

