apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-fe-next-deploy
  namespace: dlk-fe-next
spec:
  template:
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
        - name: dlk-fe-next-ecr-secret
      containers:
        - name: nextjs-container
          image: 084550838259.dkr.ecr.ap-northeast-2.amazonaws.com/dlink/next-app:v2.0.5
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_REST_API
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: KAKAO_REST_API
            - name: NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: NAVER_CLIENT_ID
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: NAVER_CLIENT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: NEXTAUTH_SECRET
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"

