apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerts
  namespace: monitoring
spec:
  groups:
    - name: cluster-rules
      rules:
        - alert: HighCPUUsage
          expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) > 0.8
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "[$labels.instance] CPU 사용량 초과"
            description: "CPU 사용률이 2분 동안 {{ humanize $value }} % 초과"

        - alert: HighMemoryUsage
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.8
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "[$labels.instance] 메모리 사용량 초과"
            description: "메모리 사용량이 2분 동안 {{ humanize $value }} % 초과"

        - alert: NodeDown
          expr: up{job="node-exporter"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "노드 다운: $labels.instance"
            description: "노드가 5분 동안 응답 없음"

        - alert: CrashLoopBackOff
          expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} == 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod $labels.pod 충돌 감지"
            description: "Pod [$labels.namespace]의 $labels.pod 이(가) CrashLoopBackOff 상태"

