
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-service
  name: dlk-be-alcohol-review-deploy
  namespace: dlk-be-alcohol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - env:
            - SPRING_DATASOURCE_URI: {} 
          image: 192.168.3.81/dlink/review-service:v2.0
          name: spring-container 
