
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: highball-service
  name: dlk-be-alcohol-highball-deploy
  namespace: dlk-be-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highball-service
  template:
    metadata:
      labels:
        app: highball-service
    spec:
      containers:
        - env:
          - {}
          image: 192.168.3.81/dlink/highball-service:v2.0
          name: spring-container

