apiVersion: v1
kind: Service
metadata: 
  name: dlk-kafka-broker1-service
  namespace: dlk-kafka
spec: 
  type: LoadBalancer 
  selector: 
    app: kafka-broker1
  ports: 
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
