apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-service
  name: dlk-be-alcohol-review-deploy
  namespace: dlk-be-alcohol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
        - name: dlk-be-alcohol-harbor-secrets
      containers:
#        - envFrom:
#            - secretRef:
#                name: dlk-be-alcohol-secrets
#            - configMapRef:
#                name: dlk-be-alcohol-config
        - image: 192.168.3.81/dlink/review-service:v2.0.0
          name: spring-container
          resources:
            requests:
              cpu: "50m"
              memory: "320Mi"
            limits:
              cpu: "1100m"
              memory: "512Mi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: "AWS_ACCESS_KEY"
              value: "/mnt/secrets/AWS_ACCESS_KEY"
            - name: "AWS_SECRET_KEY"
              value: "/mnt/secrets/AWS_SECRET_KEY"
            - name: "ES_DATASOURCE_URI"
              value: "/mnt/secrets/ES_DATASOURCE_URI"
            - name: "JWT_SECRET_KEY"
              value: "/mnt/secrets/JWT_SECRET_KEY"
            - name: "REDIS_URL"
              value: "/mnt/secrets/REDIS_URL"
            - name: "SPRING_DATA_MONGODB_URI"
              value: "/mnt/secrets/SPRING_DATA_MONGODB_URI"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
