
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
  name: dlk-be-auth-auth-deploy
  namespace: dlk-be-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: dlk-be-auth-harbor-secrets
      containers:
        - name: spring-container
          image: 192.168.3.81/dlink/auth-service:v2.0.0
#          envFrom:
#            - secretRef:
#                name: dlk-be-auth-secrets
#            - configMapRef:
#                name: dlk-be-auth-config
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: "AWS_ACCESS_KEY"
              value: "/mnt/secrets/AWS_ACCESS_KEY"
            - name: "AWS_SECRET_KEY"
              value: "/mnt/secrets/AWS_SECRET_KEY"
            - name: "GOOGLE_CLIENT_ID"
              value: "/mnt/secrets/GOOGLE_CLIENT_ID"
            - name: "GOOGLE_CLIENT_SECRET"
              value: "/mnt/secrets/GOOGLE_CLIENT_SECRET"
            - name: "KAKAO_CLIENT_SECRET"
              value: "/mnt/secrets/KAKAO_CLIENT_SECRET"
            - name: "KAKAO_REST_API"
              value: "/mnt/secrets/KAKAO_REST_API"
            - name: "NAVER_CLIENT_ID"
              value: "/mnt/secrets/NAVER_CLIENT_ID"
            - name: "NAVER_CLIENT_SECRET"
              value: "/mnt/secrets/NAVER_CLIENT_SECRET"
            - name: "NEXTAUTH_SECRET"
              value: "/mnt/secrets/NEXTAUTH_SECRET"
            - name: "ES_DATASOURCE_URI"
              value: "/mnt/secrets/ES_DATASOURCE_URI"
            - name: "JWT_SECRET_KEY"
              value: "/mnt/secrets/JWT_SECRET_KEY"
            - name: "SPRING_DATA_MONGODB_URI"
              value: "/mnt/secrets/SPRING_DATA_MONGODB_URI"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
