apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: dlk-gateway-gateway-deploy
  namespace: dlk-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
        - name: dlk-gateway-ecr-secret
      containers:
#        - envFrom:
#            - secretRef:
#                name: dlk-gateway-secrets
#            - configMapRef:
#                name: dlk-gateway-config
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"        
          image: 192.168.3.81/dlink/api-gateway:v2.0.1
          name: alcohol-container
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: "AWS_ACCESS_KEY"
              value: "/mnt/secrets/AWS_ACCESS_KEY"
            - name: "AWS_SECRET_KEY"
              value: "/mnt/secrets/AWS_SECRET_KEY"
            - name: "ES_DATASOURCE_URI"
              value: "/mnt/secrets/ES_DATASOURCE_URI"
            - name: "JWT_SECRET_KEY"
              value: "/mnt/secrets/JWT_SECRET_KEY"
            - name: "SPRING_DATA_MONGODB_URI"
              value: "/mnt/secrets/SPRING_DATA_MONGODB_URI"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
