apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs
  name: dlk-fe-next-deploy
  namespace: dlk-fe-next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
        - name: dlk-fe-next-ecr-secret
      containers:
        - name: nextjs-container
          image: 084550838259.dkr.ecr.ap-northeast-2.amazonaws.com/dlink/next-app:v2.0.5
          ports:
            - containerPort: 3000
#          envFrom:
#            - secretRef:
#                name: dlk-fe-next-secrets
#            - configMapRef:
#                name: dlk-fe-next-config
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
#            - name: "AWS_ACCESS_KEY"
#              value: "/mnt/secrets/AWS_ACCESS_KEY"
#            - name: "AWS_SECRET_KEY"
#              value: "/mnt/secrets/AWS_SECRET_KEY"
            - name: "GOOGLE_CLIENT_ID"
              value: "/mnt/secrets/GOOGLE_CLIENT_ID"
            - name: "GOOGLE_CLIENT_SECRET"
              value: "/mnt/secrets/GOOGLE_CLIENT_SECRET"
            - name: "KAKAO_CLIENT_SECRET"
              value: "/mnt/secrets/KAKAO_CLIENT_SECRET"
            - name: "KAKAO_REST_API"
              value: "/mnt/secrets/KAKAO_REST_API"
            - name: "NAVER_CLIENT_ID"
              value: "/mnt/secrets/NAVER_CLIENT_ID"
            - name: "NAVER_CLIENT_SECRET"
              value: "/mnt/secrets/NAVER_CLIENT_SECRET"
            - name: "NEXTAUTH_SECRET"
              value: "/mnt/secrets/NEXTAUTH_SECRET"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
      restartPolicy: Always

