
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alcohol-service
  name: dlk-be-alcohol-alcohol-deploy
  namespace: dlk-be-alcohol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alcohol-service
  template:
    metadata:
      labels:
        app: alcohol-service
    spec:
      imagePullSecrets:
        - name: dlk-be-alcohol-harbor-secrets
      containers:
        - envFrom:
            - secretRef:
                name: dlk-be-alcohol-secrets
          image: 192.168.3.81/dlink/alcohol-service:v2.0
          name: spring-container
