apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs
  name: dlk-fe-next-deploy
  namespace: dlk-fe-next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: dlk-fe-next-harbor-secrets
      containers:
        - name: nextjs-container
          image: 192.168.3.81/dlink/next-app:v2.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: dlk-fe-next-secrets
      restartPolicy: Always

