apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: highball-service
  name: dlk-be-alcohol-highball-deploy
  namespace: dlk-be-alcohol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highball-service
  template:
    metadata:
      labels:
        app: highball-service
    spec:
      serviceAccountName: eks-secrets-sa
      imagePullSecrets:
#        - name: dlk-be-alcohol-harbor-secrets
        - name: dlk-be-alcohol-ecr-secret
      containers:
        - envFrom:
#            - secretRef:
#                name: dlk-be-alcohol-secrets
            - configMapRef:
                name: dlk-be-alcohol-config
          image: 084550838259.dkr.ecr.ap-northeast-2.amazonaws.com/dlink/highball-service:v2.0.0 #192.168.3.81/dlink/highball-service:v2.0.0
          name: spring-container
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "1500m"
              memory: "1.25Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_KEY
            - name: ES_DATASOURCE_URI
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: ES_DATASOURCE_URI
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: JWT_SECRET_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: REDIS_URL
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: SPRING_DATA_MONGODB_URI
#            - name: AWS_ACCESS_KEY
#              value: "/mnt/secrets/AWS_ACCESS_KEY"
#            - name: AWS_SECRET_KEY
#              value: "/mnt/secrets/AWS_SECRET_KEY"
#            - name: ES_DATASOURCE_URI
#              value: "/mnt/secrets/ES_DATASOURCE_URI"
#            - name: JWT_SECRET_KEY
#              value: "/mnt/secrets/JWT_SECRET_KEY"
#            - name: REDIS_URL
#              value: "/mnt/secrets/REDIS_URL"
#            - name: SPRING_DATA_MONGODB_URI
#              value: "/mnt/secrets/SPRING_DATA_MONGODB_URI"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
